name: java-template-service-ci

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build and tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Build with gradle and run tests
        run: ./gradlew build
      - name: Report Tests
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Report for unit tests
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit
      - name: Run integration tests
        run: ./gradlew testIntegration
      - name: Report tests
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Report for integration tests
          path: build/test-results/testIntegration/TEST-*.xml
          reporter: java-junit
