name: java-template-service-ci

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: ['21']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build-DB
        run: docker-compose build

      - name: Create-DB
        run: docker-compose up -d

      - name: Test Integration
        run: ./gradlew testIntegration

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build-DB
        run: docker-compose build

      - name: Create-DB
        run: docker-compose up -d

      - name: Build
        run: ./gradlew build